
# Site settings
url: http://example.org/
title: Your awesome title
email: your-email@domain.com
description: jekyll-rdf businesscards
baseurl: ""

# Build settings
markdown: kramdown

# jekyll-rdf
plugins:
    - jekyll-rdf
jekyll_rdf:
    path: "rdf-data/content.ttl"
    restriction: "SELECT ?resourceUri WHERE {
                 { ?resourceUri a <http://example.org/group> . }
                UNION { ?resourceUri a <http://example.org/project> . }
                UNION { ?resourceUri a <http://example.org/publication> . }
                UNION { ?resourceUri a <http://xmlns.com/foaf/0.1/Person> . }
                UNION { ?resourceUri a <http://xmlns.com/foaf/0.1/Document> . }
                }"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Document" : "document.html"
