
# Site settings
url: http://example.org/
baseurl: ""

# Build settings
markdown: kramdown

# jekyll-rdf
plugins:
    - jekyll-rdf
jekyll_rdf:
    path: "rdf-data/content.ttl"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Document" : "document.html"
